### ISSUE TITLE
Unexpected exception HA 2024.8

### ISSUE THREAD

**Issue by kap46248** [wingertge/ambientika-hass#2]
I really like your integration for the Ambientika air exchanger and was really happy when I found it by chance. But since the upgrade to 2024.8 there is an unexpected error when I want to add my devices. 
<img width="797" alt="Screenshot 2024-08-22 at 23 48 53" src="https://github.com/user-attachments/assets/2ed39e94-6e88-411a-86f8-8fee44a11346">

I already tried to fix the problem but had no luck because of my lack of experience. It would be awesome if you could fix the problem.

Best regards

Patrick

**Comment by wingertge** [comment]
It seems that somehow your configuration was messed up, the URL in the error shows it's trying to connect to "23" which obviously isn't correct. Can you try to update the integration config with this host manually? (This is the default when installing the integration)
`https://app.ambientika.eu:4521`

**Comment by kap46248** [comment]
Hmm you are right. 23 isn't correct. Yesterday I pulled a docker container with version 2024.7, 2024.6, 2024.4 and it didn't work. It was a completely new home assistant config and the hacs installation was also new. Interestingly I got a message (hacs), that the repo isn't compatible which I hadn't before. Everything is so strange. Pyscript has also problems running a script to connect to a Jupyter kernel.. I think this server is cursed :D. Normally everything should work without a problem because I'm running everything in docker.

**Comment by kap46248** [comment]
> It seems that somehow your configuration was messed up, the URL in the error shows it's trying to connect to "23" which obviously isn't correct. Can you try to update the integration config with this host manually? (This is the default when installing the integration) `https://app.ambientika.eu:4521`

Thank you very much. I don't know why but I always entered the !P address instead of `https://app.ambientika.eu:4521` as a host. This solved the problem and I can finally use your genius integration again.
